// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nyltwtvesvncitgftvvb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55bHR3dHZlc3ZuY2l0Z2Z0dnZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMTcyOTksImV4cCI6MjA2NDU5MzI5OX0.OnZ8RUuaTPA4LnZDTx7yHr1IHfVvjZBKviUNMXNW9pw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);